# Generated by Django 4.0.4 on 2022-04-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='votes_total',
            field=models.IntegerField(default=0),
        ),
    ]
