# Generated by Django 4.0.4 on 2022-04-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_votes_total_vote_vote_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-vote_total']},
        ),
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
