# Generated by Django 4.0.4 on 2022-04-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_vote_options_vote_vote_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='vote_total',
        ),
    ]
